sudo: required

language: python

services:
  - docker

env:
- IMAGE_NAME=docker-pipeline
- RELEASE_URL=https://registry.hub.docker.com/u/stevencooney/docker-test/trigger/$DOCKER_HUB_TOKEN/

before_install:
  - docker --version

jobs:
  include:
    - stage: build docker image
      script:
      - docker build --pull -t $IMAGE_NAME .
      - docker images
    - stage: test
      script: docker run -i $IMAGE_NAME /bin/sh -c 'docker --version'
    - script: docker run -i $IMAGE_NAME /bin/sh -c 'docker --version'
