sudo: true
dist: trusty

before_install:
  - docker --version

env:
  - IMAGE_NAME: docker-pipeline
    RELEASE_URL: https://registry.hub.docker.com/u/stevencooney/docker-test/trigger/$DOCKER_HUB_TOKEN/

jobs:
  include:
    - stage: build & test docker image
      script:
      # Build docker image
      - docker build --pull -t $IMAGE_NAME .
      - docker images
      # Test docker image
      - docker run -i $IMAGE_NAME /bin/sh -c 'docker --version'
